image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
conda_file: ../../../AzureML/environment/train_conda.yml
description: Custom environment to train heart disease pipeline
version: 0.1.0
